---
- name: Remove hosted engine conf file
  ansible.builtin.file:
    path: "{{ hosted_engine_conf }}"
    state: absent

- name: Stop ovirt-ha-agent service
  ansible.builtin.service:
    name: ovirt-ha-agent
    state: stopped
