---
- name: Detect host operating system
  ansible.builtin.set_fact:
    el_ver: "{{ ansible_distribution_major_version | int
        if ansible_os_family == 'RedHat'
        else 0 }}"
    fc_ver: "{{ ansible_distribution_major_version | int
        if ansible_distribution == 'Fedora'
        else 0 }}"

- name: Fetch installed packages
  ansible.builtin.package_facts:
    manager: rpm

- name: Check if vdsm is preinstalled
  ansible.builtin.set_fact:
    vdsm_preinstalled: "{{ 'vdsm' in ansible_facts.packages }}"

- name: Parse operating system release
  ansible.builtin.lineinfile:
    path: /etc/os-release
    line: 'VARIANT_ID="ovirt-node"'
  check_mode: true
  register: node_presence

- name: Detect if host is a prebuilt image
  ansible.builtin.set_fact:
    node_host: "{{ not node_presence.changed }}"

- block:
    - name: Check version of ovirt-openvswitch before upgrade
      ansible.builtin.set_fact:
        ovirt_openvswitch_pre: "{{ ansible_facts.packages['ovirt-openvswitch'] | first }}"
      when:
        - ansible_facts.packages['ovirt-openvswitch'] is defined

    - name: Check version of rhv-openvswitch before upgrade
      ansible.builtin.set_fact:
        ovirt_openvswitch_pre: "{{ ansible_facts.packages['rhv-openvswitch'] | first }}"
      when:
        - ansible_facts.packages['rhv-openvswitch'] is defined

  when:
    - check_ovs_version is defined
    - check_ovs_version | bool
    - ovirt_openvswitch_pre is not defined
