---
- name: Check if ovirt-provider-ovn-driver is installed
  ansible.builtin.package:
    name: ovirt-provider-ovn-driver
    state: present
  check_mode: true
  register: ovn_packages

- name: Unconfigure the OVN chassis
  ansible.builtin.command: vdsm-tool ovn-unconfigure # noqa no-handler
  when: not ovn_packages.changed
