---
# rc 5 = Physical volume '/dev/name' is already in volume group
- name: Setup SSD for caching | Extend the Volume Group
  ansible.builtin.command: "vgextend --dataalignment 256K {{ vgname }} {{ ssd }}"
  register: resp
  failed_when: resp.rc not in [0, 5]
  changed_when: resp.rc == 0

# rc 5 = Physical volume '/dev/name' is already in volume group
- name: Setup SSD for caching | Create LV for cache
  ansible.builtin.command: "lvcreate -L {{ cache_lvsize }} -n {{ cache_lvname }} {{ vgname }}"
  register: resp
  failed_when: resp.rc not in [0, 5]
  changed_when: resp.rc == 0

- name: Setup SSD for caching | Create metadata LV for cache
  ansible.builtin.command: "lvcreate -L {{ cache_meta_lvsize }} -n {{ cache_meta_lv }} {{ vgname }}"
  when: cache_meta_lv is defined and cache_meta_lv != ' '
  register: resp
  failed_when: resp.rc not in [0, 5]
  changed_when: resp.rc == 0

- name: Setup SSD for caching | Convert logical volume to a cache pool LV
  ansible.builtin.command: >
     lvconvert -y --type cache-pool --poolmetadata {{ cache_meta_lv }}
        --poolmetadataspare n
        --cachemode {{ cachemode | default('writethrough') }}
        "/dev/{{ vgname }}/{{ cache_lvname }}"
  when: cache_meta_lv is defined and cache_meta_lv != ' '
  register: resp
  failed_when: resp.rc not in [0, 5]
  changed_when: resp.rc == 0

# rc 5 = Command on LV name/cache does not accept LV type cachepool.
# It is valid not to have cachemetalvname! Writing a separate task not to
# complicate things.
- name: Setup SSD for caching | Convert logical volume to a cache pool LV without cachemetalvname
  ansible.builtin.command: >
     lvconvert -y --type cache-pool
        --poolmetadataspare n
        --cachemode {{ cachemode | default('writethrough') }}
        "/dev/{{ vgname }}/{{ cache_lvname }}"
  when: cache_meta_lv is not defined
  register: resp
  failed_when: resp.rc not in [0, 5]
  changed_when: resp.rc == 0

# Run lvs -a -o +devices to see the cache settings
- name: Setup SSD for caching | Convert an existing logical volume to a cache LV
  ansible.builtin.command: >
     lvconvert -y --type cache --cachepool "/dev/{{ vgname }}/{{ cache_lvname }}"
     "/dev/{{ vgname }}/{{ lvname }}_pool"
  register: resp
  failed_when: resp.rc not in [0, 5]
  changed_when: resp.rc == 0
