- name: Make sure authorized_keys file is present
  ansible.builtin.stat:
    path: "/root/.ssh/authorized_keys"
  register: authkey

- name: Copy the authorized_keys from the active host to the new host
  ansible.posix.synchronize:
    src: "/root/.ssh/authorized_keys"
    dest: "/root/.ssh/authorized_keys"
    mode: pull
  delegate_to: "{{ gluster_new_node | mandatory }}"
  connection: ssh
  when: authkey.stat.isreg is defined
