---
- name: Rename the OVA file
  ansible.builtin.command: mv "{{ ova_file.dest }}" "{{ target_directory }}/{{ ova_name }}"
  async: "{{ ansible_timeout }}"
  poll: 15
  when: packing_result.rc is defined and packing_result.rc == 0

- name: Remove the temporary file
  ansible.builtin.file:
    path: "{{ ova_file.dest }}"
    state: absent
  when: packing_result.rc is defined and packing_result.rc != 0

- name: Check OVA creation process result
  ansible.builtin.fail:
    msg: "Failed to create OVA file"
  when: packing_result.rc is defined and packing_result.rc != 0
