- hosts: all
  remote_user: root

  # https://github.com/ansible/ansible/issues/10698
  # Make sure we use LANG=C for the yum plugin, to properly parse the updated/installed
  # packages
  environment:
    LANG: "C"

  pre_tasks:
    - include_vars: ovirt_host_upgrade_vars.yml

    - include: ovirt-host-yum-conf.yml

    - block:
      # Check if certificates need re-enrollment:
      - name: Check host certificate validity
        command: |
          '/usr/bin/openssl'
          'verify'
          '-attime'
          "{{ ovirt_time_to_check }}"
          '-CAfile'
          "{{ item.ca }}"
          "{{ item.cert }}"
        with_items:
          - 'ca': "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_ca_file }}"
            'cert': "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_cert_file }}"
          - 'ca': "{{ ovirt_vdsm_trust_store }}/{{ ovirt_qemu_ca_file }}"
            'cert': "{{ ovirt_vdsm_trust_store }}/{{ ovirt_qemu_cert_file }}"
          - 'ca': "{{ ovirt_libvirt_default_trust_store }}/{{ ovirt_libvirt_default_client_ca_file }}"
            'cert': "{{ ovirt_libvirt_default_trust_store }}/{{ ovirt_libvirt_default_client_cert_file }}"
          - 'ca': "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_spice_ca_file }}"
            'cert': "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_spice_cert_file }}"
        register: iscorrect
        # If the certificate is invalid, an error code is returned and we must proceed, not stop.
        ignore_errors: yes

      - name: Get host certificate info
        shell: >
          openssl x509 -in "{{ ovirt_vdsm_trust_store }}/{{ ovirt_vdsm_cert_file }}" -text -noout
          -certopt no_subject,no_header,no_version,no_serial,no_signame,no_validity,no_subject,no_issuer,no_pubkey,no_sigdump,no_aux
          | awk '/X509v3 Subject Alternative Name/','/X509v3 Basic Constraints/'
        register: host_certificate

      - name: Check if host certificate contains subject alternative name
        set_fact:
          contains_san: "{{ host_certificate.stdout is search(ovirt_vds_hostname) }}"

      - name: Check if QEMU migration client certificates are present
        stat:
          path: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_qemu_client_cert_file }}"
        register: qemu_client_cert_stat

      - name: Check if OVN certificates are present
        stat:
          path: "{{ ovirt_vdsm_trust_store }}/{{ ovirt_ovn_cert_file }}"
        register: ovn_client_cert_stat

      - name: Set enrollment variable
        set_fact:
          do_host_cert_enrollment: >-
            {{ ('error' in iscorrect.results | map(attribute='stdout') | join(' '))
            or not contains_san
            or not qemu_client_cert_stat.stat.exists
            or not ovn_client_cert_stat.stat.exists }}
      when: not ansible_check_mode

  roles:
    - name: ovirt-host-deploy-facts
    - name: ovirt-host-enroll-certificate
      when: do_host_cert_enrollment is defined and do_host_cert_enrollment
    - name: ovirt-host-upgrade
    - name: ovirt-host-deploy-vnc-certificates

  post_tasks:
    - include: ovirt-host-remove-yum-conf.yml
    - include: ovirt-host-reconfigure-ovn.yml
