- name: Populate service facts and restart libvirtd
  ansible.builtin.service_facts:
  register: services_in_vnc_sasl
  changed_when: true
  notify:
    restart libvirtd

# libvirtd may not be started automatically on hosts >= 4.4 if not
# already running.
- name: Restart libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: restarted
  when: "services_in_vnc_sasl['ansible_facts']['services'].get('libvirtd.service', {}).get('state') == 'running'"
  listen: "restart libvirtd"
