name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            shortcut: cs8
            container-name: stream8

    name: ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts
      MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"

    container:
      image: quay.io/centos/centos:${{ matrix.container-name }}

    steps:
    - name: Prepare CentOS Stream 8 environment
      if: ${{ matrix.shortcut == 'cs8' }}
      run: |
        # Install oVirt repositories
        dnf copr enable -y ovirt/ovirt-master-snapshot centos-stream-8
        dnf install -y ovirt-release-master

        # Requried for python3-ansible-lint and python3-isort
        dnf copr enable -y sbonazzo/EL8_collection

        # Configure CS8 repositories
        dnf config-manager --enable powertools
        dnf module enable -y pki-deps javapackages-tools

    - name: Install required packages
      run: |
        dnf install -y \
          createrepo_c \
          dnf-utils \
          git \
          gzip \
          java-11-openjdk-devel \
          make \
          maven \
          python3-ansible-lint \
          python3-pycodestyle \
          python3-pytest \
          python3-pytest-mock \
          python3-devel \
          python3-isort \
          python3-pyflakes \
          python3-pyOpenSSL \
          python3-dnf-plugin-versionlock \
          rpm-build \
          sed \
          tar

    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Use cache for maven
      uses: actions/cache@v2
      with:
        path: "${{ github.workspace }}/repository"
        key: ${{ matrix.shorcut }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ matrix.shorcut }}-maven-

    - name: Perform build
      run: |
        make all-dev \
          BUILD_GWT=1 \
          DEV_BUILD_GWT_DRAFT=1 \
          BUILD_UT=1 \
          BUILD_JAVA_OPTS_GWT="-Xms1G -Xmx4G" \
          DEV_EXTRA_BUILD_FLAGS_GWT_DEFAULTS="-Dgwt.userAgent=gecko1_8,safari" \
          DEV_EXTRA_BUILD_FLAGS="-Dgwt.compiler.localWorkers=1"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rpm-${{ matrix.shortcut }}
        path: ${{ env.ARTIFACTS_DIR}}
