name: build
on:
  push:
    branches: [master, ovirt-engine-4.5.0.z]
  pull_request:
    branches: [master, ovirt-engine-4.5.0.z]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            shortcut: cs8
            container-name: el8stream
          # Try to enable CS9 after switch to xmaven is finished
          # - name: centos-stream-9
          #  shortcut: cs9
          #  container-name: stream9

    name: ${{ matrix.name }}

    env:
      ARTIFACTS_DIR: exported-artifacts

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Setup maven cache
      uses: actions/cache@v2
      with:
        path: /root/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Perform build
      run: |
        .automation/build-rpm.sh $ARTIFACTS_DIR

    - name: Create DNF repository
      run: |
        createrepo_c $ARTIFACTS_DIR

    - name: Upload artifacts
      uses: ovirt/upload-rpms-action@v2
      with:
        directory: ${{ env.ARTIFACTS_DIR }}
