---
- name: Include sync. clock tasks
  ansible.builtin.include_tasks: clock.yml

- name: Include gluster tasks
  ansible.builtin.include_tasks: gluster.yml
  when: host_deploy_gluster_supported|bool

- name: Include tuned profile tasks
  ansible.builtin.include_tasks: tuned_profile.yml
  when: not (host_deploy_tuned_profile == 'null' and not host_deploy_virt_enabled|bool)
