---
- name: Get lastest tune package
  yum:
    name: tuned
    state: present

- name: Start tune service
  service:
    name: tuned
    state: started

- name: Set tune profile
  shell: "tuned-adm profile {{ host_deploy_tuned_profile }}"
  register: tune_profile_set
  tags:
    - skip_ansible_lint # E305

- name: Enable tune service
  service:
    name: tuned
    enabled: yes
  when: tune_profile_set.rc == 0
