- name: Check if VDSM config file exists
  ansible.builtin.stat:
    path: "{{ ovirt_vdsm_config_file }}"
  register: vdsm_conf_stat

- block:
    - name: Temporary file for vdsm configuration
      ansible.builtin.tempfile:
        state: file
        suffix: tempvdsmtrustore
      register: tempvdsmconf
      delegate_to: localhost

    - name: Load vdsm trust store location
      ansible.builtin.fetch:
        src: "{{ ovirt_vdsm_config_file }}"
        dest: "{{ tempvdsmconf.path }}"
        flat: true

    - name: Set VDSM truststore path
      ansible.builtin.set_fact:
        ovirt_vdsm_trust_store: "{{ lookup('ini', 'trust_store_path section=vars file=' ~ tempvdsmconf.path) or ovirt_vdsm_trust_store }}"

  when: vdsm_conf_stat.stat.exists
  always:
    - name: Remove temp VDSM config file
      ansible.builtin.file:
        state: absent
        path: "{{ tempvdsmconf.path }}"
      when: tempvdsmconf is defined
